### ISSUE TITLE
Pages Module

### ISSUE THREAD

**Issue by marvinkome** [marvinkome/contento#2]
- [ ] All pages UI
- [ ] UI for creating pages
- [ ] UI for editing pages
- [ ] UI for deleting pages
- [ ] CRUD for pages
- [ ] exposing pages API
